### ISSUE TITLE
Error reading environment variables

### ISSUE THREAD

**Issue by phillipahereza** [sparkplug/momoapi-python#25]
**Describe the bug**

There's an error when reading in the `REMITTANCE_PRIMARY_KEY` environment variable. A simple typo is the keyword [`os.envieon`](https://github.com/sparkplug/momoapi-python/blob/8b93092f03594dfa3012e9d7c73cf7f15e075122/src/mtnmomo/config.py#L21) instead of `os.environ`

**Comment by raybesiga** [comment]
Thank you for catching this @phillipahereza!
