### ISSUE TITLE
Continuous Integration and Testing

### ISSUE THREAD

**Issue by raybesiga** [sparkplug/momoapi-python#3]
We need to add CI to facilitate automation of testing and publishing. We shall use Travis CI.
For the start, the CI should publish to `pip` when a PR is reviewed and merged to master.

Progress

- [ ] configure pylint
- [ ] configure testing
- [ ] configure semantic versioning
- [ ] configure [travis ci](travis-ci.org)
- [ ] add appropriate `pypi` token and github token to Travis CI secrets

**Comment by mossplix** [comment]
Python does not deploy to NPM. I have added the pypi secret though

**Comment by raybesiga** [comment]
Thanks for the correction. Updated.
