### ISSUE TITLE
Please I need help on how to integrate this into django app

### ISSUE THREAD

**Issue by timessuman** [sparkplug/momoapi-python#32]
kindly help me

**Comment by raybesiga** [comment]
Hi @Tim38-code please follow the README. Usage section.

**Comment by timessuman** [comment]
Thank you @raybesiga, I have done exactly that, but I am trying to call it in my view. That is where I am  having difficulties. And also the form to allow users to enter their phone numbers

**Comment by raybesiga** [comment]
I think you need to learn how Django works. Here is a link: https://www.djangoproject.com/start/ Best regards.
