### ISSUE TITLE
Gitpitch deck shutting down.

### ISSUE THREAD

**Issue by ma-za-kpe** [sparkplug/momoapi-python#34]
This (https://gitpitch.com/sparkplug/momo-developer-training-slides/master) momo API training will be no more when git pitch finally shuts down from march 1st 2021. 

And since many people are using the API, and looking for such helpful resources, the tutorial should be moved to an open-source platform like GitHub README.

Since this link is embedded in the training docs,

**Comment by raybesiga** [comment]
Hi @ma-za-kpe 

Thanks for pointing this out. However, not to worry, we have the training docs here on Github. You can see the language-specific training modules here:

[NodeJS](https://github.com/sparkplug/momo-nodejs-developer-training-slides)
[Python](https://github.com/sparkplug/momo-python-developer-training-slides)
[PHP](https://github.com/sparkplug/momo-php-developer-training-slides)
[Java](https://github.com/sparkplug/momo-java-developer-training-slides)

This should be even more useful.

**Comment by raybesiga** [comment]
Going to go ahead and close this issue now
